[package]
name = "router_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.79", features = ["full"] }
quote = "1.0.37"
serde_json = "1.0.68"
serde = { version = "1.0.130", features = ["derive"] }
proc-macro2 = "1.0.87"