[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.68"
serde = { version = "1.0.130", features = ["derive"] }
enum_dispatch = "0.3.13"
router_macro = { path = "./router_macro" }